## This is a configuration file for the different parameters used in the project

###### Filter parameters ######
## Voxel downsampling parameter -> float: for sphere extraction
voxel_down_sample: 0.75
## Sphere radius -> int: for sphere extraction
sphere_radius: 10
## Filtering radius -> float: for outlier removal
filtering_radius: 0.2
## Number of neighbors -> int: for outlier removal
num_neighbors: 10
## Std ratio -> float: for outlier removal
std_ratio: 0.5

###### GICP parameters ######
## Maximum correspondence distance, step 1 -> float
max_cor_dist_1: 3.0
## Maximum correspondence distance, step 2 -> float
max_cor_dist_2: 1.0

###### Topics and Frames ######
## Frame ID -> str: for visualization
frame_id: 'map'
## Robot 1 map topic -> str
m1_topic: '/robot1/map'
## Robot 2 map topic -> str
m2_topic: '/robot2/map'

